---
title: "replicating_ppcs"
author: "Brenda Fried"
date: "7/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(scales)
```

```{r}
load('ppcs_1999.RData')
load('ppcs_1996.RData')
load('ppcs_2008.RData')
load('ppcs_2005.RData')
load('ppcs_2002.RData')
load('ppcs_2011.RData')

merged_ppcs <- rbind(ppcs_1996_cleaned, ppcs_1999_cleaned, ppcs_2008_cleaned, ppcs2002_polished, ppcs2005_polished, ppcs_2011)

```

```{r}
#percentage of races from whole sample
merged_ppcs %>%
  group_by(civilian_race) %>%
  summarize(count = n()) %>% 
  mutate(prop = count/sum(count))
```

```{r}
#percentage of male and female from whole sample
merged_ppcs %>%
  group_by(civilian_gender) %>%
  summarize(count = n()) %>%
  mutate(prop = count/sum(count))
```
#Proportions of gender per race
```{r}

merged_ppcs %>%
  group_by(civilian_race) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  group_by(civilian_race, civilian_gender) %>%
  mutate(gender_count = n()) %>% 
  mutate(prop = gender_count/count) %>%
ggplot() +
  geom_point(aes(x = civilian_race, y = prop)) +
  facet_wrap(~ civilian_gender) 

# merged_ppcs %>%
#   group_by(civilian_race) %>%
#   mutate(count = n()) %>%
#   ungroup() %>%
#   group_by(civilian_race, civilian_gender) %>%
#   mutate(gender_count = n()) %>% 
#   mutate(prop = gender_count/count) %>%
#   ungroup() %>%
#   ggplot() +
#   geom_linerange(aes(x = civilian_race, ymax = prop, ymin = 0)) +
#   facet_wrap(~ civilian_gender) 
```
#average age
```{r}
merged_ppcs %>%
  select(civilian_age) %>% 
  filter(civilian_age != 'missing/ni/ou') %>%
  mutate(civilian_age = as.numeric(civilian_age)) %>%
  summarize(mean = mean(civilian_age))
```
```{r}
merged_ppcs %>%
  filter(civilian_age != 'missing/ni/ou') %>%
  mutate(civilian_age = as.numeric(civilian_age)) %>%
  group_by(civilian_race) %>%
  summarize(mean = mean(civilian_age))
```

##Civilian Employed
```{r}
merged_ppcs %>%
  group_by(civilian_race) %>%
  mutate(count = n(), civilian_employed = as.numeric(civilian_employed)) %>%
  ungroup() %>%
  group_by(civilian_race, civilian_employed) %>%
  summarize(employed_count = n()) %>% 
  ungroup() %>%
  group_by(civilian_race) %>%
  mutate(sum = sum(employed_count)) %>%
  filter(civilian_employed == 1) %>%
  mutate(prop = employed_count/sum)
  
```
#Income
```{r income-full-sample}
merged_ppcs %>%
  filter(year != 1996 & year != 2008) %>%
  summarise(mean = mean(civilian_income, na.rm = TRUE))
  
  
```
```{r}
#Check for outliers
merged_ppcs %>%
  group_by(year) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  group_by(year, civilian_income) %>%
  mutate(income_count = n()) %>% 
  mutate(prop = income_count/count) %>% 
  ggplot(aes(x = year, y = prop)) +
  geom_point() +
  facet_wrap(~ civilian_income)
```


```{r income-by-race}
merged_ppcs %>%
  group_by(civilian_race) %>%
  summarise(mean = mean(civilian_income, na.rm = TRUE))
```
#Population Size
```{r}
#check for outliers
merged_ppcs %>%
  group_by(year) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  group_by(year, population_size) %>%
  mutate(pop_count = n()) %>% 
  mutate(prop = pop_count/count) %>% 
  ggplot(aes(x = year, y = prop)) +
  geom_point() +
  facet_wrap(~ population_size)
```

```{r pop-size-full-sample}
merged_ppcs %>%
  summarise(mean = mean(population_size, na.rm = TRUE))
```
```{r pop-size-by-race}
merged_ppcs %>%
  group_by(civilian_race) %>%
  summarise(mean = mean(population_size, na.rm = TRUE))
```

#Incident Type
We are missing all street stop
```{r}
merged_ppcs %>%
  filter(is.na(type_of_incident) != TRUE) %>%
  mutate(type_of_incident = as.factor(type_of_incident)) %>%
  group_by(civilian_race) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  group_by(civilian_race, type_of_incident) %>%
  summarise(c = n()) %>%
  ungroup() %>%
  group_by(civilian_race) %>%
  mutate(sum = sum(c)) %>%
  mutate(prop = c/sum) %>% view
  ggplot() +
  geom_point(aes(x = type_of_incident, y = prop, color = type_of_incident)) +
  facet_wrap(~ civilian_race)
```

```{r}
#check for outliers
merged_ppcs %>%
  group_by(year) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  group_by(year, type_of_incident) %>%
  mutate(incident_count = n()) %>% 
  mutate(prop = incident_count/count) %>% 
  ggplot(aes(x = year, y = prop)) +
  geom_point() +
  facet_wrap(~ type_of_incident)
```

##Time of Encounter
```{r}
#Check for outliers
merged_ppcs %>%
  group_by(year) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  group_by(year, time_of_encounter) %>%
  mutate(encounter_count = n()) %>% 
  mutate(prop = encounter_count/count) %>% 
  ggplot(aes(x = year, y = prop)) +
  geom_point() +
  facet_wrap(~ time_of_encounter)
```

```{r time-of-encounter-full-sample}
merged_ppcs %>%
  group_by(time_of_encounter) %>%
  filter(is.na(time_of_encounter) != TRUE ) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  mutate(prop = count/ sum(count))


```

```{r time-of-encounter-by-race}
merged_ppcs %>%
  filter(is.na(time_of_encounter) != TRUE ) %>%
  group_by(civilian_race) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  group_by(civilian_race, time_of_encounter) %>%
  summarize(enc_count = n()) %>% 
  ungroup() %>%
  group_by(civilian_race) %>%
  mutate(sum = sum(enc_count)) %>%
  mutate(prop = enc_count/sum)

```
## Civilian Behavior
```{r}
#check for outliers
merged_ppcs %>%
  group_by(year) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  group_by(year, civilian_behavior) %>%
  mutate(beh_count = n()) %>% 
  mutate(prop = beh_count/count) %>% 
  ggplot(aes(x = year, y = prop)) +
  geom_point() +
  facet_wrap(~ civilian_behavior)
```

```{r}
merged_ppcs %>%
  group_by(civilian_behavior) %>%
  summarise(count = n()) %>% view
  
```
#Officer Race
```{r}
merged_ppcs %>%
  mutate(off_race = case_when(
    (off_black == 1) ~ 'black',
    (off_white == 1) ~ 'white',
    (off_other == 1) ~ 'other'
  )) %>%
  filter(is.na(off_race) == FALSE) %>%
  group_by(off_race) %>%
  summarise(count = n()) %>%
  mutate(prop = count/sum(count))
```

##Alternative outcomes

```{r}
#check for outliers
merged_ppcs %>%
  group_by(year) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  group_by(year, civilian_searched) %>%
  mutate(search_count = n()) %>% 
  mutate(prop = search_count/count) %>%  view
  ggplot(aes(x = year, y = prop)) +
  geom_point() +
  facet_wrap(~ civilian_searched)
```

```{r alt-outcomes-full-sample}
merged_ppcs %>%
  group_by(civilian_searched) %>%
  summarise(count = n()) %>%
  mutate(prop = count/sum(count))
```
```{r}
merged_ppcs %>%
  group_by(civilian_race) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  group_by(civilian_race, civilian_searched) %>%
  summarise(search_count = n()) %>%
  mutate(prop = search_count/sum(search_count)) %>%
  filter(civilian_searched == 1)
```

```{r}
#check for outliers
merged_ppcs %>%
  group_by(year) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  group_by(year, civilian_arrested) %>%
  mutate(arr_count = n()) %>% 
  mutate(prop = arr_count/count) %>% 
  ggplot(aes(x = year, y = prop)) +
  geom_point() +
  facet_wrap(~ civilian_arrested)
```
```{r}
merged_ppcs %>%
  group_by(civilian_arrested) %>%
  summarise(count = n()) %>%
  mutate(prop = count/sum(count))
```


```{r}
merged_ppcs %>%
  group_by(civilian_race) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  group_by(civilian_race, civilian_arrested) %>%
  summarise(arrest_count = n()) %>%
  mutate(prop = arrest_count/sum(arrest_count)) %>%
  filter(civilian_arrested == 1)

```

```{r}
#check for outliers
merged_ppcs %>%
  group_by(year) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  group_by(year, civilian_guilty_of_illegal) %>%
  mutate(guilt_count = n()) %>% 
  mutate(prop = guilt_count/count) %>% 
  ggplot(aes(x = year, y = prop)) +
  geom_point() +
  facet_wrap(~ civilian_guilty_of_illegal)
```
```{r}
merged_ppcs %>%
  group_by(civilian_guilty_of_illegal) %>%
  summarise(count = n()) %>%
  mutate(prop = count/sum(count))
```
```{r}
merged_ppcs %>%
  group_by(civilian_race) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  group_by(civilian_race, civilian_guilty_of_illegal) %>%
  summarise(guilt_count = n()) %>%
  mutate(prop = guilt_count/sum(guilt_count)) %>%
  filter(civilian_guilty_of_illegal == 1)
```

