---
title: "ppcs_regression"
author: "Brenda Fried"
date: "7/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(modelr)
library(tidyverse)
load("merged_ppcs.RData")
```

```{r}
merged_ppcs <- merged_ppcs %>%
  mutate(civilian_race = factor(civilian_race, levels = c('white', 'black', 'other', 'hispanic')),
         civilian_age = as.numeric(civilian_age),
         off_hispanic = 0)


options(na.action = "na.omit")
```


```{r}
logit <- glm(force ~ civilian_race, family = "binomial", data= merged_ppcs)
exp(coef(logit))
summary(logit)
```

```{r}
logit1 <- glm(force ~ civilian_race + civilian_gender + civilian_income + civilian_employed + population_size + I(civilian_age^2), family='binomial', data = merged_ppcs)
summary(logit1)
exp(coef(logit1))
```
```{r}
logit2 <- glm(force ~ civilian_race + civilian_gender + civilian_income + civilian_employed + population_size + I(civilian_age^2) + time_of_encounter + type_of_incident + off_hispanic + off_white + off_black + off_other + off_split, family='binomial', data = merged_ppcs)
summary(logit2)
exp(coef(logit2))
```

```{r}
logit3 <- glm(force ~ civilian_race + civilian_gender + civilian_income + civilian_employed + population_size + I(civilian_age^2) + time_of_encounter + type_of_incident + off_hispanic + off_white + off_black + off_other + off_split + civilian_behavior, family='binomial', data = merged_ppcs)
summary(logit3)
exp(coef(logit3))
```

```{r}
logit4 <- glm(force ~ civilian_race + civilian_gender + civilian_income + civilian_employed + population_size + I(civilian_age^2) + time_of_encounter + type_of_incident + off_hispanic + off_white + off_black + off_other + off_split + civilian_behavior + year, family='binomial', data = merged_ppcs)
summary(logit4)
exp(coef(logit4))
```


#Regression for at least grabbed
Need to filter for all non-misisng use of force data
```{r}
#not missing 
filtered_merged_ppcs <- merged_ppcs %>% filter(force != 0)
```

```{r}
at_lst_grab_model1 <- glm(at_least_grabbed ~ civilian_race, family = "binomial", data= merged_ppcs)
exp(coef(at_lst_grab_model1))
summary(at_lst_grab_model1)
```

```{r}
at_lst_grab_model2 <- glm(at_least_grabbed ~ civilian_race + civilian_gender + civilian_employed + civilian_income + population_size + I(civilian_age^2), family = "binomial", data = merged_ppcs)

exp(coef(at_lst_grab_model2))
summary(at_lst_grab_model2)
```

