---
title: "plots"
author: "Cindy"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
######################################ALTERNATIVE OUTCOME PLOTS###############################################
```



```{r}
library(tidyverse)
library(lubridate)
library(scales)
library(ggplot2)
theme_set(theme_bw())
```


```{r}
load("merged_ppcs.RData")
```

```{r}
fryers_prop <- c(0.16, 0.10, 0.13, NA)

merged_guilty <- merged_ppcs %>% 
  group_by(civilian_race, civilian_guilty_of_illegal) %>%
  summarize(count_of_guilty_civilian= n()) %>%
  mutate(prop = count_of_guilty_civilian / sum(count_of_guilty_civilian)) %>% 
  mutate(se = sqrt((prop*(1 - prop)) / sum(count_of_guilty_civilian))) %>% 
  filter(civilian_guilty_of_illegal == 1) %>% 
  ungroup() %>%
  mutate(fry_prop = fryers_prop) %>%
  ggplot(aes(x = civilian_race, y = prop)) + 
  labs(x = "Civilian Race", y = "Proportion") +
  geom_point(aes(x = civilian_race, y = fry_prop), shape = "X", size = 3.5, color = "red") +
   geom_pointrange(aes(ymin = prop - se, ymax = prop + se)) +
  ggtitle("Proportions of Civilians Guilty\nof Carrying Illegal Items by Race") +
  scale_y_log10() 

merged_guilty

ggsave("ppcs_civilian_guilty_of_carrying_illegal_items.png", plot = merged_guilty, width=3.5, height =4 )

  
```

```{r}
fryers_prop <- c(0.02, 0.05, 0.04, NA)

merged_ppcs %>% 
  group_by(civilian_race, civilian_arrested) %>%
  summarize(count_of_arrested= n()) %>%
  mutate(prop = count_of_arrested/ sum(count_of_arrested)) %>% 
  mutate(se = sqrt((prop*(1 - prop)) / sum(count_of_arrested))) %>% 
  filter(civilian_arrested == 1) %>% 
  ungroup() %>%
  mutate(fry_prop = fryers_prop) %>%
  ggplot(aes(x = civilian_race, y = prop)) + 
  labs(x = "Civilian Race", y = "Proportion") +
   geom_pointrange(aes(ymin = prop - se, ymax = prop + se)) +
  geom_point(aes(x = civilian_race, y = fry_prop), shape = "X", size = 3.5, color = "red") +
  ggtitle("Proportions of Civilians Arrested by Race")
```

```{r}
fryers_prop <- c(0.04, 0.11, 0.09, NA)

merged_ppcs %>% 
  group_by(civilian_race, civilian_searched) %>%
  summarize(count_of_searched= n()) %>%
  mutate(prop = count_of_searched/ sum(count_of_searched)) %>% 
  mutate(se = sqrt((prop*(1 - prop)) / sum(count_of_searched))) %>% 
  filter(civilian_searched == 1) %>% 
  ungroup() %>%
  mutate(fry_prop = fryers_prop) %>%
  ggplot(aes(x = civilian_race, y = prop)) + 
  labs(x = "Civilian Race", y = "Proportion") +
   geom_pointrange(aes(ymin = prop - se, ymax = prop + se)) +
  geom_point(aes(x = civilian_race, y = fry_prop), shape = "X", size = 3.5, color = "red") +
  ggtitle("Proportions of Civilians Searched by Race")
```

```{r}
fryers_prop <- c(0.01, 0.02, 0.02, NA)

excess_force_plot <- merged_ppcs %>% 
  group_by(civilian_race, excess_force) %>%
  summarize(count_excess_force = n()) %>%
  mutate(prop = count_excess_force/ sum(count_excess_force)) %>% 
  mutate(se = sqrt((prop*(1 - prop)) / sum(count_excess_force))) %>% 
  filter(excess_force == 1) %>% 
  ungroup() %>%
  mutate(fry_prop = fryers_prop) %>%
  ggplot(aes(x = civilian_race, y = prop)) + 
  labs(x = "Civilian Race", y = "Proportion") +
   geom_pointrange(aes(ymin = prop - se, ymax = prop + se)) +
  geom_point(aes(x = civilian_race, y = fry_prop), shape = "X", size = 3.5, color = "red") +
  ggtitle("Proportions of Civilians Perceiving Excess Force by Race")

ggsave("ppcs_proportion_civilians_perceiving_excess_force_by_race.png", plot = excess_force_plot,
       width = 10, height = 6)
```

```{r}
fryers_prop <- c(0, 0, 0, NA)

merged_ppcs %>% 
  group_by(civilian_race, civilian_injured) %>%
  summarize(count_of_injured= n()) %>%
  mutate(prop = count_of_injured/ sum(count_of_injured)) %>% 
  mutate(se = sqrt((prop*(1 - prop)) / sum(count_of_injured))) %>% 
  filter(civilian_injured == 1) %>% 
  ungroup() %>%
  mutate(fry_prop = fryers_prop) %>%
  ggplot(aes(x = civilian_race, y = prop)) + 
  labs(x = "Civilian Race", y = "Proportion") +
  geom_pointrange(aes(ymin = prop - se, ymax = prop + se)) +
  geom_point(aes(x = civilian_race, y = fry_prop), shape = "X", size = 3.5, color = "red") +
  ggtitle("Proportions of Civilians Injured by Race")
```



