---
title: "ppcs_2011"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
#CREATED PPCS_2011 DATAFRAME
ppcs_2011 <- da34276.0001
```



```{r}
#RACE
ppcs_2011_new <- ppcs_2011 %>% 
  mutate(civilian_race =  case_when(RACE == '(01) White Only' ~ 'white',
                                    RACE == '(02) Black Only' ~ 'black',
                                    HISP == '(1) Respondent is Hispanic' ~ 'hispanic',
                                    TRUE ~ 'other')) 
```



```{r}
#AGE                                 
ppcs_2011_new <- ppcs_2011 %>% 
  mutate(civilian_age = AGE) 
```

```{r}
#INCOME
ppcs_2011_new <- ppcs_2011 %>% 
  mutate(civilian_income = case_when(INCOME =='(1) Less than $20,000 or NA' ~ 1, 
                                     INCOME == '(2) $20,000 - $49,999' ~ 2,
                                     INCOME == '(3) $50,000 or more' ~ 3)) 

```


```{r}
#GENDER
ppcs_2011_new <- ppcs_2011 %>% 
  mutate(civilian_gender = SEX) %>% 
  mutate(civilian_gender = as.factor(civilian_gender)) 
summary(ppcs_2011_new$civilian_gender)
```


```{r}
#EMPLOYED
ppcs_2011_new <- ppcs_2011 %>% 
  mutate(civilian_employed = case_when(WORK == '(1) Yes' ~ 1,
                                      WORK == '(2) No' ~ 0,
                                      TRUE ~ 0)) 
```


```{r}
#POPULATION
ppcs_2011_new <- ppcs_2011 %>%
  mutate(civilian_income = case_when(PLACE == '(1) Under 100,000/Not in a place' ~ 1, 
                                     PLACE == '(2) 100,000-499,999' ~ 2,
                                     PLACE == '(3) 500,000-999,999' ~ 3,
                                     PLACE == '(4) 1 million or more' ~ 4)) 
```


```{r}
#TIME OF ENCOUNTER
ppcs_2011_new <- ppcs_2011 %>% 
 mutate(time_of_encounter = case_when(
   (V81 == ('(01) After 6 a.m. - 12 noon')| 
      V204 == ('(01) After 6 a.m. - 12 noon')) ~1,
   (V81 == ('(02) After 12 noon - 6 p.m.')|
      V204 == ('(02) After 12 noon - 6 p.m.')) ~2, 
    (V81 == ('(01) After 6 a.m. - 12 noon')| 
       V204 == ('(01) After 6 a.m. - 12 noon'))~3,
     (V81 == ('(04) After 6 p.m. - 12 midnight')| 
        V204 == ('(04) After 6 p.m. - 12    midnight')) ~ 4,
      (V81 == ('(05) After 12 midnight - 6 a.m.')| 
         V204 == ('(05) After 12 midnight - 6 a.m.')) ~ 5,
       (V81 == ("(06) Don't know what time of night")| 
          V204 == ("(06) Don't know what time of night")) ~ 6,
        TRUE ~ NA_real_))
```


```{r}
#OFFICER RACE 
ppcs_2011_new <- ppcs_2011 %>%
  select(V74, V75, V76, V77, V78, V79, V80) %>% 
  mutate(off_black = case_when(V76 == '(1) Black or African American' ~ 1, TRUE ~ 0))%>%
  mutate(off_white = case_when(V74 == '(1) White' ~ 1, TRUE ~ 0)) %>%
  mutate(off_hispanic = case_when(V74 == '(1) Yes' ~ 1, 
                                  V74 == '(2) No' ~ 0, TRUE ~ 0)) %>%
  mutate(off_other = case_when(
    (V77 == '(1) American Indian or Alaska Native' |  
    V78 == '(1) Asian' |
    V79 == 'Native Hawaiian or other Pacific Islander' |
    V80 == "(1) Don't know") ~ 0, TRUE ~ 0)) 
```


```{r}
#CIVILIAN BEHAVIOR
ppcs_2011_new <- ppcs_2011 %>%
  mutate(civilian_behavior = case_when(V399 == '(1) Yes' ~ 1,
                                       V399 == '(2) No' ~ 0,
                                       (V401 == ('(1) Yes')| V166 == ('(1) Yes')) ~ 1,
                                       (V401 == ('(2) No')| V166 == ('(2) No')) ~ 0,
                                       V168 == '(1) Yes' ~ 1,
                                       V168 == '(2) No' ~ 0,
                                       (V405 == ('(1) Yes')| V170 == ('(1) Yes')) ~ 1,
                                       (V405 == ('(2) No')| V170 == ('(2) No')) ~ 0,
                                       V172 == '(1) Yes' ~ 1,
                                       V172 == '(2) No' ~ 0,
                                       V174 == '(1) Yes' ~ 1,
                                       V174 == '(2) No' ~ 0,
                                       (V398 == ('(1) Yes')| V176 == ('(1) Yes')) ~ 1,
                                       (V398 == ('(2) No')| V176 == ('(2) No')) ~ 0,
                                       (V407 == ('(1) Yes')| V178 == ('(1) Yes')) ~ 1,
                                       (V407 == ('(2) No')| V178 == ('(2) No')) ~ 0,
                                       TRUE ~ NA_real_)) 
```


```{r}
#ALTERNATIVE OUTCOMES
ppcs_2011_new <- ppcs_2011 %>%
  
  mutate(civilian_searched = case_when(V183 == '(1) Yes' ~ 1, 
                                       V183 == '(2) No' ~ 0, TRUE ~ NA_real_)) %>%
  mutate(civilian_arrested = case_when(V182 == '(1) Yes' ~ 1, 
                                       V182 == '(2) No' ~ 0, TRUE ~ NA_real_)) %>%
  mutate(civilian_guilty_of_illegal = case_when(V187 == '(1) Yes' ~ 1, 
                                                V187 == '(2) No' ~ 0, TRUE ~ NA_real_))
```


```{r}
#TYPE OF INCIDENT
#Interpretations of columns V55, V56, V57, V58,V59, V60, V61, V62, V63, V64 are unclear  
ppcs_2011_new <- ppcs_2011 %>% 
   mutate(type_of_incident = case_when(V39 == '(1) Yes' ~ 1,
                                       V39 == '(2) No' ~ 0,
                                       (V41 == ('(1) Yes')| V166 == ('(1) Yes')) ~ 1,
                                       (V41 == ('(2) No')| V166 == ('(2) No')) ~ 0,
                                       V43 == '(1) Yes' ~ 1,
                                       V43 == '(2) No' ~ 0,
                                       (V45 == ('(1) Yes')| V170 == ('(1) Yes')) ~ 1,
                                       (V45 == ('(2) No')| V170 == ('(2) No')) ~ 0,
                                       V47 == '(1) Yes' ~ 1,
                                       V47 == '(2) No' ~ 0,
                                       V49 == '(1) Yes' ~ 1,
                                       V49 == '(2) No' ~ 0,
                                       V51 == '(1) Yes' ~ 1,
                                       V51 == '(2) No' ~ 0,
                                       V53 == '(1) Yes' ~ 1,
                                       V53 == '(2) No' ~ 0,
                                       TRUE ~ NA_real_)) 
```


```{r}
#YEAR
ppcs_2011_new <- ppcs_2011 %>%
  mutate(year = 2011) %>%
  mutate(year = factor(year, levels = c(2011)))
```


```{r}
ppcs_2011_clean <- ppcs_2011_new %>%
  select(civilian_race,
         civilian_age,
         civilian_gender,
         civilian_income,
         civilian_employed,
         population_size,
         time_of_encounter,
         off_black,
         off_white,
         off_other,
         type_of_incident,
         civilian_behavior,
         civilian_searched,
         civilian_arrested,
         civilian_guilty_of_illegal,
         year
         )

 

save(ppcs_2011_clean, file = 'ppcs_2011_clean.Rdata')
```

