---
title: "ppcs_regression"
author: "Brenda Fried"
date: "7/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(modelr)
library(tidyverse)
load("merged_ppcs.RData")
```


#Regression for at least grabbed
added columns according to fryer
```{r}
merged_ppcs <- merged_ppcs %>% mutate(
    at_least_grabbed_fry = ifelse(
      grab_push == 1 |
      handcuffed == 1|
      point_gun == 1 |
      hit_kick == 1  |
      pepper_stun == 1, 1, 0),
    
    at_least_handcuffed_fry = case_when(
     (handcuffed == 1|
      point_gun == 1 |
      hit_kick == 1  |
      pepper_stun == 1) ~ 1,
     (grab_push == 1) ~NA_real_,
     TRUE ~ 0),
    
    at_least_point_gun_fry = case_when(
      (point_gun == 1 |
      hit_kick == 1  |
      pepper_stun == 1) ~ 1,
      (grab_push == 1 | handcuffed == 1) ~ NA_real_,
    TRUE ~ 0),

    at_least_kick_pepper_stun_fry = case_when(
      (hit_kick == 1  |
      pepper_stun == 1) ~ 1,
      (grab_push == 1 | handcuffed == 1 | point_gun == 1) ~ NA_real_,
      TRUE ~ 0),
    
    at_least_grabbed_fry = as.factor(at_least_grabbed_fry),
    at_least_handcuffed_fry = as.factor(at_least_handcuffed_fry),
    at_least_point_gun_fry = as.factor(at_least_point_gun_fry),
    at_least_kick_pepper_stun_fry = as.factor(at_least_kick_pepper_stun_fry)
)

```


```{r}
at_least_grab_model1 <- glm(at_least_grabbed_fry ~ civilian_race, family = "binomial", data= merged_ppcs)
exp(coef(at_least_grab_model1))
summary(at_least_grab_model1)
```

```{r}
at_least_grab_model2 <- glm(at_least_grabbed_fry ~ civilian_race + civilian_gender + civilian_employed + civilian_income + population_size + I(civilian_age^2), family = "binomial", data = merged_ppcs)

exp(coef(at_least_grab_model2))
summary(at_least_grab_model2)
```

```{r}
at_least_grab_model3 <- glm(at_least_grabbed_fry ~ civilian_race + civilian_gender + civilian_employed + civilian_income + population_size + I(civilian_age^2) + time_of_encounter + type_of_incident + off_white + off_black + off_hispanic + off_other + off_hispanic + off_split, family = "binomial", data = merged_ppcs)

exp(coef(at_least_grab_model3))
summary(at_least_grab_model3)

summary(merged_ppcs)
```

```{r}
at_least_grab_model4 <- glm(at_least_grabbed_fry  ~ civilian_race + civilian_gender + civilian_employed + civilian_income + population_size + I(civilian_age^2) + time_of_encounter + type_of_incident + off_white + off_black + off_hispanic + off_other + off_hispanic + off_split + civilian_behavior, family = "binomial", data = merged_ppcs)

exp(coef(at_least_grab_model4))
summary(at_least_grab_model4)
```

```{r}

at_least_grab_model5 <- glm(at_least_grabbed ~ civilian_race + civilian_gender + civilian_employed + civilian_income + population_size + I(civilian_age^2) + time_of_encounter + type_of_incident + off_white + off_black + off_hispanic + off_other + off_hispanic + off_split + civilian_behavior + year, family = "binomial", data = merged_ppcs)

exp(coef(at_least_grab_model5))
summary(at_least_grab_model5)
```


#At least handcuffed
```{r}
at_least_handcuffed_model1 <- glm(at_least_handcuffed_fry ~ civilian_race, family = "binomial", data = merged_ppcs)

summary(at_least_handcuffed_model1)
exp(coef(at_least_handcuffed_model1))
```

```{r}
at_least_handcuffed_model2 <- glm(at_least_handcuffed_fry ~ civilian_race+ civilian_gender + civilian_employed + civilian_income + population_size + I(civilian_age^2), family = "binomial", data = merged_ppcs)

summary(at_least_handcuffed_model2)
exp(coef(at_least_handcuffed_model2))
```

```{r}
at_least_handcuffed_model3 <- glm(at_least_handcuffed_fry ~ civilian_race + civilian_gender + civilian_employed + civilian_income + population_size + I(civilian_age^2) + time_of_encounter + type_of_incident + off_white + off_black + off_other + off_hispanic + off_split, family = "binomial", data = merged_ppcs)

exp(coef(at_least_handcuffed_model3))
summary(at_least_handcuffed_model3)
```

```{r}
at_least_handcuffed_model4 <- glm(at_least_handcuffed_fry ~ civilian_race + civilian_gender + civilian_employed + civilian_income + population_size + I(civilian_age^2) + time_of_encounter + type_of_incident + off_white + off_black + off_other + off_hispanic + off_split + civilian_behavior, family = "binomial", data = merged_ppcs)

exp(coef(at_least_handcuffed_model4))
summary(at_least_handcuffed_model4)
```
```{r}
at_least_handcuffed_model5 <- glm(at_least_handcuffed_fry ~ civilian_race + civilian_gender + civilian_employed + civilian_income + population_size + I(civilian_age^2) + time_of_encounter + type_of_incident + off_white + off_black + off_other + off_hispanic + off_split + civilian_behavior + year, family = "binomial", data = merged_ppcs)

exp(coef(at_least_handcuffed_model5))
summary(at_least_handcuffed_model5)
```
#At least point Gun Regressions
```{r}
at_least_point_gun_model1 <- glm(at_least_point_gun_fry ~ civilian_race, family = "binomial", data = merged_ppcs)

summary(at_least_point_gun_model1)
exp(coef(at_least_point_gun_model1))
```

```{r}
at_least_point_gun_model2 <- glm(at_least_point_gun_fry ~ civilian_race + civilian_gender + civilian_employed + civilian_income + population_size + I(civilian_age^2), family = "binomial", data = merged_ppcs)

summary(at_least_point_gun_model2)
exp(coef(at_least_point_gun_model2))
```

```{r}
at_least_point_gun_model3 <- glm(at_least_point_gun ~ civilian_race + civilian_gender + civilian_employed + civilian_income + population_size + I(civilian_age^2) + time_of_encounter + type_of_incident + off_white + off_black + off_other + off_hispanic + off_split, family = "binomial", data = merged_ppcs)

exp(coef(at_least_point_gun_model3))
summary(at_least_point_gun_model3)
```


```{r}
at_least_point_gun_model4 <- glm(at_least_point_gun ~ civilian_race + civilian_gender + civilian_employed + civilian_income + population_size + I(civilian_age^2) + time_of_encounter + type_of_incident + off_white + off_black + off_other + off_hispanic + off_split + civilian_behavior, family = "binomial", data = merged_ppcs)

exp(coef(at_least_point_gun_model4))
summary(at_least_point_gun_model4)
```
```{r}
at_least_point_gun_model5 <- glm(at_least_point_gun_fry ~ civilian_race + civilian_gender + civilian_employed + civilian_income + population_size + I(civilian_age^2) + time_of_encounter + type_of_incident + off_white + off_black + off_other + off_hispanic + off_split + civilian_behavior + year, family = "binomial", data = merged_ppcs)

exp(coef(at_least_point_gun_model5))
summary(at_least_point_gun_model5)

```
#At least kick and pepper spray
```{r}
at_least_kick_pepper_stun_model1 <- glm(at_least_kick_pepper_stun_fry ~ civilian_race, family = "binomial", data = merged_ppcs)

summary(at_least_kick_pepper_stun_model1)
exp(coef(at_least_kick_pepper_stun_model1))
```

```{r}
at_least_kick_pepper_stun_model2 <- glm(at_least_kick_pepper_stun_fry ~ civilian_race + civilian_gender + civilian_employed + civilian_income + population_size + I(civilian_age^2), family = "binomial", data = merged_ppcs)

summary(at_least_kick_pepper_stun_model2)
exp(coef(at_least_kick_pepper_stun_model2))
```

```{r}
at_least_kick_pepper_stun_model3 <- glm(at_least_kick_pepper_stun_fry ~ civilian_race + civilian_gender + civilian_employed + civilian_income + population_size + I(civilian_age^2) + time_of_encounter + type_of_incident + off_white + off_black + off_other + off_hispanic + off_split, family = "binomial", data = merged_ppcs)

exp(coef(at_least_kick_pepper_stun_model3))
summary(at_least_kick_pepper_stun_model3)
```

```{r}
at_least_kick_pepper_stun_model4 <- glm(at_least_kick_pepper_stun_fry ~ civilian_race + civilian_gender + civilian_employed + civilian_income + population_size + I(civilian_age^2) + time_of_encounter + type_of_incident + off_white + off_black + off_other + off_hispanic + off_split + civilian_behavior, family = "binomial", data = merged_ppcs)

exp(coef(at_least_kick_pepper_stun_model4))
summary(at_least_kick_pepper_stun_model4)
```
```{r}
at_least_kick_pepper_stun_model5 <- glm(at_least_kick_pepper_stun_fry ~ civilian_race + civilian_gender + civilian_employed + civilian_income + population_size + I(civilian_age^2) + time_of_encounter + type_of_incident + off_white + off_black + off_other + off_hispanic + off_split + civilian_behavior + year, family = "binomial", data = merged_ppcs)

exp(coef(at_least_kick_pepper_stun_model5))
summary(at_least_kick_pepper_stun_model5)
```

