---
title: "PPCS 2005 Data Clean"
output: html_notebook
---

```{r load libraries and dataset}
library(tidyverse)
# loading in the dataset
ppcs2005 <- read_tsv("20020-0001-Data.tsv")
```
```{r filter incidents}
ppcs2005 <- ppcs2005 %>%
  filter(v10 == 1)
```


```{r civilian_race column}
# white and not hispanic
# black and black-hispanic
# hispanic
# other
ppcs2005 <- ppcs2005 %>% 
  mutate(civilian_race = case_when(
    (v5 == 1 & v6 == 2) ~ "white", # white and not hispanic
    (v5 == 2) ~ "black", # black and black-hispanic
    (v6 == 1 & v5 != 2) ~ "hispanic", # hispanic
    TRUE ~ "other" # other
  ))
  # )) %>%
  # mutate(civilian_race = factor(civilian_race, 
  #                               levels = c("black",
  #                               "hispanic",
  #                               "other",
  #                               "white")))
summary(ppcs2005$civilian_race)
```

```{r civilian_age}
ppcs2005 <- ppcs2005 %>% 
  mutate(civilian_age = v4)
summary(ppcs2005$civilian_age)
```

```{r civilian_gender}
# male
# female
# NA (not applicable to this dataset)
ppcs2005 <- ppcs2005 %>%
  mutate(civilian_gender = v3)
  # ) %>%
  # mutate(civilian_gender = factor(civilian_gender,
  #                                 levels = c(1,2)))

summary(ppcs2005$civilian_gender)

```

```{r civilian_income}
# 1 - less than 20k or NA
# 2 - 20k - 50k
# 3 - greater than 50k
ppcs2005 <- ppcs2005 %>%
  mutate(civilian_income = income)
  #        ) %>%
  # mutate(civilian_income = factor(civilian_income,
  #                                 levels = c(1,2,3)))

summary(ppcs2005$civilian_income)
```

```{r civilian_employed}
# 1 - employed
# 2 - not employed
ppcs2005 <- ppcs2005 %>%
  mutate(civilian_employed = case_when(
                              (work == 1) ~ 1,
                              TRUE ~ 0))
  # )) %>%
  # mutate(civilian_employed = factor(civilian_employed,
  #                                   levels = c(1,0)))
summary(ppcs2005$civilian_employed)
```

```{r population_size}
# 1 - no response or population under 100k
# 2 - 100k - 499,999
# 3 - 500k - 999,999
# 4 - 1 million or more
ppcs2005 <- ppcs2005 %>%
  mutate(population_size = place)
  # ) %>%
  # mutate(population_size = factor(population_size,
  #                                 levels = c(1,2,3,4)))
summary(ppcs2005$population_size)
```

```{r time_of_encounter}
# 1 - 6am - 12 noon
# 2 - 12 noon - 6pm 
# 3 - day time but not specified
# 4 - 6 pm - 12 midnight
# 5 - 12 midnight - 6am 
# 6 - night time but not specified
ppcs2005 <- ppcs2005 %>%
  mutate(time_of_encounter = case_when(
                              v48 == 1 ~ 6,
                              v48 == 2 ~ 3,
                              TRUE ~ NA_real_
  ))
  # )) %>%
  # mutate(time_of_encounter = factor(time_of_encounter,
  #                                   levels = c(1,2,3,4,5,6)))
summary(ppcs2005$time_of_encounter)
```

```{r officer_race}
## off_black
# 1 - yes
# 2 - no
## off_white
# 1 - yes
# 2 - no
## off_other
# 1 - yes
# 2 - no
ppcs2005 <- ppcs2005 %>%
  mutate(off_black = case_when((v46 == 2 | v47 == 2 | v47 == 5) ~ 1,
                               TRUE ~ 0
    )) %>%
  mutate(off_white = case_when((v46 == 1 | v47 == 1 | v47 == 4) ~ 1,
                               TRUE ~ 0
                               )) %>% 
  mutate(off_other = case_when((v46 == 3 | v47 == 3 | v47 %in% c(6,7)) ~ 1,
                               TRUE ~ 0
  ))
  # )) %>%
  # mutate(off_black = factor(off_black,
  #                           levels = c(0,1))) %>%
  # mutate(off_white = factor(off_white,
  #                           levels = c(0,1))) %>%
  # mutate(off_other = factor(off_other,
  #                           levels = c(0,1)))
summary(ppcs2005$off_black)
summary(ppcs2005$off_white)
summary(ppcs2005$off_other)
```

```{r type_of_incident}
# 1 - street stop
# 2 - traffic stop
# 3 - other
ppcs2005 <- ppcs2005 %>%
  mutate(type_of_incident = case_when((reason %in% c(2,3)) ~ 2,
                                      (reason %in% c(1,4:8)) ~ 3
  ))
  # )) %>%
  # mutate(type_of_incident = factor(type_of_incident,
  #                                  levels = c(1,2,3)))
summary(ppcs2005$type_of_incident)
```

```{r civilian_behavior}
# 1 - yes if any conditions are met
# 0 - none of the conditions are met
ppcs2005 <- ppcs2005 %>%
  mutate(civilian_behavior = 0)
  # ) %>%
  # mutate(civilian_behavior = factor(civilian_behavior,
  #                                   levels = c(0,1)))
summary(ppcs2005$civilian_behavior)
```

```{alt_outcomes}
## civilian_searched
# 1 - yes
# 2 - no
## civilian_arrested
# 1 - yes
# 2 - no
## civilian_guilty_of_illegal
# 1 - yes
# 2 - no
ppcs2005 <- ppcs2005 %>%
  mutate(civilian_searched = case_when((v75 == 1 | v83 == 1) ~ 1,
                                       TRUE ~ 0)) %>%
  mutate(civilian_arrested = case_when((v61 == 1 | v82 == 1) ~ 1,
                                       TRUE ~ 0)) %>%
  mutate(civilian_guilty_of_illegal = case_when((v56 == 1 | v78 == 1) ~ 1,
                                       TRUE ~ 0))
  # )) %>%
  # mutate(civilian_searched = factor(civilian_searched,
  #                                   levels = c(0,1))) %>%
  # mutate(civilian_arrested = factor(civilian_arrested,
  #                                   levels = c(0,1))) %>%
  # mutate(civilian_guilty_of_illegal = factor(civilian_guilty_of_illegal,
  #                                   levels = c(0,1)))

summary(ppcs2005$civilian_searched)
summary(ppcs2005$civilian_arrested)
summary(ppcs2005$civilian_guilty_of_illegal)
```

```{r year}
ppcs2005 <- ppcs2005 %>%
  mutate(year = 2005)
  # ) %>%
  # mutate(year = factor(year, levels = c(2005)))
summary(ppcs2005$year)
```

```{r final dataframe}
ppcs2005_polished <- ppcs2005 %>%
  select(civilian_race,
         civilian_age,
         civilian_gender,
         civilian_income,
         civilian_employed,
         population_size,
         time_of_encounter,
         off_black,
         off_white,
         off_other,
         type_of_incident,
         civilian_behavior,
         civilian_searched,
         civilian_arrested,
         civilian_guilty_of_illegal,
         year
         )

save(ppcs2005_polished, file = 'ppcs2005.Rdata')
```
