---
title: "PPCS 2002 Data Clean"
output: html_notebook
---

```{r load libraries and dataset}
library(asciiSetupReader)
library(tidyverse)
# loading in the dataset
ppcs2002 <- sas_ascii_reader('04273-0001-Data.txt','04273-0001-Setup.sas')
```

```{r civilian_race column}
# white and not hispanic
# black and black-hispanic
# hispanic
# other
ppcs2002 <- ppcs2002 %>% 
  mutate(civilian_race = case_when(
    (RACE_OF_RESPONDENT == "White" & HISPANIC_ORIGIN_OF_RESPONDENT == "No") ~ "white", # white and not hispanic
    (RACE_OF_RESPONDENT == "Black") ~ "black", # black and black-hispanic
    (HISPANIC_ORIGIN_OF_RESPONDENT == "Yes" & RACE_OF_RESPONDENT != "Black") ~ "hispanic", # hispanic
    TRUE ~ "other" # other
  )) %>%
  mutate(civilian_race = factor(civilian_race, 
                                levels = c("black",
                                           "hispanic",
                                           "other",
                                           "white")))
summary(ppcs2002$civilian_race)
```

```{r civilian_age}
ppcs2002 <- ppcs2002 %>% 
  mutate(civilian_age = AGE_OF_RESPONDENT)
summary(ppcs2002$civilian_age)
```

```{r civilian_gender}
# male
# female
# NA (not applicable to this dataset)
ppcs2002 <- ppcs2002 %>%
  mutate(civilian_gender = case_when((SEX_OF_RESPONDENT == "Male") ~ 1,
                                     (SEX_OF_RESPONDENT == "Female") ~ 2
    )) %>%
  mutate(civilian_gender = factor(civilian_gender,
                                  levels = c(1,2)))

summary(ppcs2002$civilian_gender)
```

```{r civilian_income}
# 1 - less than 20k or NA
# 2 - 20k - 50k
# 3 - greater than 50k
  ppcs2002 <- ppcs2002 %>%
  mutate(civilian_income = INCOME) %>%
  mutate(civilian_income = factor(civilian_income,
                                  levels = c(1,2,3)))

summary(ppcs2005$civilian_income)
```

```{r civilian_employed}
# 1 - employed
# 2 - not employed
ppcs2002 <- ppcs2002 %>%
  mutate(civilian_employed = case_when(
    (HAD_JOB_OR_WORKED_AT_A_BUSINESS_LAST_WEEK == "Yes") ~ 1,
    (HAD_JOB_OR_WORKED_AT_A_BUSINESS_LAST_WEEK == "No") ~ 0, 
    TRUE ~ NA_real_)) %>%
  mutate(civilian_employed = factor(civilian_employed,
                                    levels = c(1,0)))
summary(ppcs2002$civilian_employed)
```

```{r population_size}
# 1 - no response or population under 100k
# 2 - 100k - 499,999
# 3 - 500k - 999,999
# 4 - 1 million or more
ppcs2002 <- ppcs2002 %>%
  mutate(population_size = case_when((SIZE_OF_JURISDICTION_WHERE_RESPONDENT_RESIDED == "Under 100,000/not in a place") ~ 1,
                                     (SIZE_OF_JURISDICTION_WHERE_RESPONDENT_RESIDED == "100,000-499,999") ~ 2,
                                     (SIZE_OF_JURISDICTION_WHERE_RESPONDENT_RESIDED == "500,000-999,999") ~ 3,
                                     (SIZE_OF_JURISDICTION_WHERE_RESPONDENT_RESIDED == "1 million or more") ~ 4
  )) %>%
  mutate(population_size = factor(population_size,
                                  levels = c(1,2,3,4)))
summary(ppcs2002$population_size)
```

```{r time_of_encounter}
# 1 - 6am - 12 noon
# 2 - 12 noon - 6pm 
# 3 - day time but not specified
# 4 - 6 pm - 12 midnight
# 5 - 12 midnight - 6am 
# 6 - night time but not specified
ppcs2002 <- ppcs2002 %>%
  mutate(time_of_encounter = case_when(
    TRAFFIC_STOP_AT_NIGHT == "Yes" ~ 6,
    TRAFFIC_STOP_AT_NIGHT == "No" ~ 3,
    TRUE ~ NA_real_
  )) %>%
  mutate(time_of_encounter = factor(time_of_encounter,
                                    levels = c(1,2,3,4,5,6)))
summary(ppcs2002$time_of_encounter)
```

```{r officer_race}
## off_black
# 1 - yes
# 2 - no
## off_white
# 1 - yes
# 2 - no
## off_other
# 1 - yes
# 2 - no
ppcs2002 <- ppcs2002 %>%
  mutate(off_black = case_when((RACE_OF_OFFICER_BLACK == "Yes" | RACE_OF_OFFICERS == "Mostly black") ~ 1,
                               TRUE ~ 0
  )) %>%
  mutate(off_white = case_when((RACE_OF_OFFICER_WHITE == "Yes" | RACE_OF_OFFICERS == "Mostly white") ~ 1,
                               TRUE ~ 0
  )) %>% 
  mutate(off_other = case_when((RACE_OF_OFFICER_OTHER_RACE == "Yes" | RACE_OF_OFFICERS %in% c("Mostly some other race","Equal number of each race")) ~ 1,
                               TRUE ~ 0
  )) %>%
  mutate(off_black = factor(off_black,
                            levels = c(0,1))) %>%
  mutate(off_white = factor(off_white,
                            levels = c(0,1))) %>%
  mutate(off_other = factor(off_other,
                            levels = c(0,1)))
summary(ppcs2002$off_black)
summary(ppcs2002$off_white)
summary(ppcs2002$off_other)
```

```{r type_of_incident}
# 1 - street stop
# 2 - traffic stop
# 3 - other
ppcs2002 <- ppcs2002 %>%
  mutate(type_of_incident = case_when((TRAFFIC_STOP == "Yes") ~ 2,
                                      TRUE ~ 3
  )) %>%
  mutate(type_of_incident = factor(type_of_incident,
                                   levels = c(1,2,3)))
summary(ppcs2002$type_of_incident)
```

```{r civilian_behavior}
# 1 - yes if any conditions are met
# 0 - none of the conditions are met
ppcs2002 <- ppcs2002 %>%
  mutate(civilian_behavior = case_when((DISOBEYED_OR_INTERFERED_WITH_POLICE == "Yes") ~ 1,
                                       (TRIED_TO_GET_AWAY_FROM_POLICE == "Yes") ~ 1,
                                       (PUSHED_GRABBED_OR_HIT_OFFICER == "Yes") ~ 1,
                                       (CHARGED_WITH_RESISTING_ARREST == "Yes") ~ 1,
                                       (ARGUED_CURSED_INSULTED_OR_THREATENED_POLICE == "Yes") ~ 1,
                                       (CHARGED_WITH_ASSAULTING_OFFICER == "Yes") ~ 1,
                                       TRUE ~ 0
)) %>%
  mutate(civilian_behavior = factor(civilian_behavior,
                                    levels = c(0,1)))
summary(ppcs2002$civilian_behavior)
```

```{r alt_outcomes}
## civilian_searched
# 1 - yes
# 2 - no
## civilian_arrested
# 1 - yes
# 2 - no
## civilian_guilty_of_illegal
# 1 - yes
# 2 - no
ppcs2002 <- ppcs2002 %>%
  mutate(civilian_searched = case_when((SEARCH_OF_DRIVER_OR_VEHICLE %in% c("Yes")) ~ 1,
                                       TRUE ~ 0)) %>%
  mutate(civilian_searched = case_when((SEARCH_OCCURRED_BEFORE_ARREST %in% c("Yes")) ~ 1,
                                       TRUE ~ 0)) %>%
  mutate(civilian_searched = case_when((OTHER_CONTACT_PERSONAL_SEARCH %in% c("Yes")) ~ 1,
                                       TRUE ~ 0)) %>%
  mutate(civilian_arrested = case_when((ARRESTED_DURING_CONTACT == "Yes") ~ 1,
                                       TRUE ~ 0)) %>%
  mutate(civilian_guilty_of_illegal = case_when((ILLEGAL_DRUGS_FOUND %in% c("Yes")) ~ 1,
                                       TRUE ~ 0)) %>%
  mutate(civilian_guilty_of_illegal = case_when((ILLEGAL_WEAPON_S_FOUND %in% c("Yes")) ~ 1,
                                                TRUE ~ 0)) %>%
  mutate(civilian_guilty_of_illegal = case_when((OPEN_CONTAINER_OF_ALCOHOL_FOUND %in% c("Yes")) ~ 1,
                                                TRUE ~ 0)) %>%
  mutate(civilian_searched = factor(civilian_searched,
                                    levels = c(0,1))) %>%
  mutate(civilian_arrested = factor(civilian_arrested,
                                    levels = c(0,1))) %>%
  mutate(civilian_guilty_of_illegal = factor(civilian_guilty_of_illegal,
                                             levels = c(0,1)))

summary(ppcs2002$civilian_searched)
summary(ppcs2002$civilian_arrested)
summary(ppcs2002$civilian_guilty_of_illegal)
```

```{r year}
ppcs2002 <- ppcs2002 %>%
  mutate(year = 2002) %>%
  mutate(year = factor(year, levels = c(2002)))
summary(ppcs2002$year)
```

```{r final dataframe}
ppcs2002_polished <- ppcs2002 %>%
  select(civilian_race,
         civilian_age,
         civilian_gender,
         civilian_income,
         civilian_employed,
         population_size,
         time_of_encounter,
         off_black,
         off_white,
         off_other,
         type_of_incident,
         civilian_behavior,
         civilian_searched,
         civilian_arrested,
         civilian_guilty_of_illegal,
         year
  )

save(ppcs2002_polished, file = 'ppcs2002.Rdata')
```
