---
title: '20190722'
author: "Adnan Hoq"
date: "7/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-libraries}
library(tidyverse)
library(naniar)
library(scales)
```


```{r load-data}
load("../../raw_data/sqf_03_13.Rdata")
```


```{r logistic-models}

log_panel_data <- sf_data1 %>%
  # filter out unknown races, unknown genders, ages outside of the range 10-90,
  # and types of id equal to "other"
  filter(race != " " & race != "U" & race != "X" & sex != "Z" & typeofid != "O" &
           age > 10 & age <= 90) %>%
  # recode Black Hispanic as Black, American Indian as Other
  mutate(race = recode_factor(race,"P" = "B", "I" = "Z"),
         # create an any_force_used column - ADDED pf_other TO THIS CALCULATION
         any_force_used = paste(pf_hands, pf_grnd, pf_wall, pf_drwep, pf_ptwep,
                                pf_hcuff,pf_baton, pf_pepsp, sep = ""),
         # create factors from columns
         any_force_used = as.factor(if_else(grepl("Y",any_force_used), 1, 0)),
         sex = as.factor(if_else(grepl("M",sex), 1, 0)),
         inout = as.factor(if_else(grepl("I",inout), 1, 0)),
         timestop = as.numeric(timestop),
         daytime = as.factor(ifelse(600<=timestop & timestop<=1700,"1","0")),
         ac_incid = as.factor(if_else(grepl("Y",ac_incid), 1, 0)),
         ac_time = as.factor(if_else(grepl("Y",ac_time), 1, 0)),
         offunif = as.factor(if_else(grepl("Y",offunif), 1, 0)),
         othpers = as.factor(if_else(grepl("Y",othpers), 1, 0)),
         cs_objcs = as.factor(if_else(grepl("Y",cs_objcs), 1, 0)),
         cs_descr = as.factor(if_else(grepl("Y",cs_descr), 1, 0)),
         cs_casng = as.factor(if_else(grepl("Y",cs_casng), 1, 0)),
         cs_lkout = as.factor(if_else(grepl("Y",cs_lkout), 1, 0)),
         cs_cloth = as.factor(if_else(grepl("Y",cs_cloth), 1, 0)),
         cs_drgtr = as.factor(if_else(grepl("Y",cs_drgtr), 1, 0)),
         cs_furtv = as.factor(if_else(grepl("Y",cs_furtv), 1, 0)),
         cs_vcrim = as.factor(if_else(grepl("Y",cs_vcrim), 1, 0)),
         cs_bulge = as.factor(if_else(grepl("Y",cs_bulge), 1, 0)),
         cs_other = as.factor(if_else(grepl("Y",cs_other), 1, 0)),
         wepnfnd = paste(contrabn,asltweap,pistol,riflshot,knifcuti,machgun,othrweap, sep = ""),
         wepnfnd = as.factor(if_else(grepl("Y",wepnfnd), 1, 0)),
         pf_pp_spray_baton = paste(pf_pepsp, pf_baton,sep = ""),
         # CHANGED Y/N TO 1/0
         pf_pp_spray_baton = as.factor(ifelse(grepl("Y",pf_pp_spray_baton), 1, 0)),
         year = as.factor(year),
         addrpct = as.factor(addrpct),
         # recode race names for clarity
         race = recode_factor(race, "W" = "White", "B" = "Black",  "Q" ="Hispanic",
                              "A" = "Asian", "Z" = "Other"))


mylogit <- glm(any_force_used ~ race + sex + I(age^2) + inout + daytime + ac_incid + ac_time +
                 offunif + typeofid + othpers + cs_bulge + cs_cloth + cs_casng + cs_lkout +
                 cs_descr + cs_drgtr + cs_furtv + cs_vcrim +
                 cs_objcs + cs_other + wepnfnd + addrpct + year,
               data = log_panel_data,
               family = "binomial")


model_no_cntrl <- glm(any_force_used ~ race,
                           data = log_panel_data,
                           family = "binomial")

exp(coef(model_no_cntrl))

```

```{r}

hours <- sf_data1 %>%
  # filter out unknown races, unknown genders, ages outside of the range 10-90,
  # and types of id equal to "other"
  filter(race != " " & race != "U" & race != "X" & sex != "Z" & typeofid != "O" &
           age > 10 & age <= 90) %>%
  # recode Black Hispanic as Black, American Indian as Other
  mutate(race = recode_factor(race,"P" = "B", "I" = "Z"),
         # create an any_force_used column - ADDED pf_other TO THIS CALCULATION
         any_force_used = paste(pf_hands, pf_grnd, pf_wall, pf_drwep, pf_ptwep,
                                pf_hcuff,pf_baton, pf_pepsp, sep = ""),
         # create factors from columns
         any_force_used = if_else(grepl("Y",any_force_used), 1, 0),
         timestop = as.numeric(timestop),
         # recode race names for clarity
         race = recode_factor(race, "W" = "White", "B" = "Black",  "Q" ="Hispanic",
                              "A" = "Asian", "Z" = "Other")) %>%
  mutate(hour = str_sub(timestop, 0, -3))

  

panel_B_white <- hours %>% filter(race == "White") %>%
  group_by(hour) %>% select(hour, any_force_used) %>%
  ungroup() %>% group_by(hour) %>% 
  summarize(avg_force = mean(any_force_used), CI = 2 * (sd(any_force_used)/sqrt(n()))) %>%
  filter(!is.na(hour) & hour != "") %>% 
  mutate(hour = as.numeric(hour)) %>%
  arrange(hour)

panel_B_black <- hours %>% filter(race == "Black") %>%
  group_by(hour) %>% select(hour, any_force_used) %>%
  ungroup() %>% group_by(hour) %>% 
  summarize(avg_force = mean(any_force_used), CI = 2 * (sd(any_force_used)/sqrt(n()))) %>%
  filter(!is.na(hour) & hour != "") %>% 
  mutate(hour = as.numeric(hour)) %>%
  arrange(hour)

ggplot() + 
  geom_line(data = panel_B_white, mapping = aes(x = hour, y = avg_force)) +
  geom_pointrange(data = panel_B_white, aes(x = hour, y = avg_force, 
                                            ymin = avg_force - CI, ymax = avg_force + CI)) +
  geom_line(data = panel_B_black, mapping = aes(x = hour, y = avg_force)) +
  geom_pointrange(data = panel_B_black, aes(x = hour, y = avg_force, 
                                            ymin = avg_force-CI, ymax = avg_force + CI)) +
  ylim(.05, .3) + scale_x_continuous(breaks = c(0:23))

```